### PR TITLE
Add an option on group config to trim.

### PR DESCRIPTION
**Pull request by Nahikariii**
Also downgraded Q to avoid errors.

### CODE REVIEW

**Comment by grahamrhay** [comment]
what's changed with Q?

**Comment by uorbe001** [comment]
@grahamrhay on the unstable version (v2+) they deprecated `fncall` which is used all over the place here

**Comment by uorbe001** [comment]
it makes little sense we were using the unstable version anyway...

**Comment by grahamrhay** [comment]
true

**Pull request merged**
